apiVersion: apps/v1
kind: Deployment
metadata:
  name: commission
  namespace: mybnb
  labels:
    app: commission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commission
  template:
    metadata:
      labels:
        app: commission
    spec:
      containers:
        - name: commission
          image: 496278789073.dkr.ecr.ap-northeast-2.amazonaws.com/mybnb-commission:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: api.url.payment
              valueFrom:
                configMapKeyRef:
                  name: mybnb-config
                  key: api.url.payment
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: v1
kind: Service
metadata:
  name: commission
  namespace: mybnb
  labels:
    app: commission
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: commission
